parameters:
    mopa_bootstrap.navbar.generic: Mopa\Bundle\BootstrapBundle\Navbar\GenericNavbar

services:
    mopa_bootstrap.subnavbar_renderer:
        class: Mopa\Bundle\BootstrapBundle\Navbar\Renderer\SubnavbarRenderer
        arguments: [ @service_container, %mopa_bootstrap.subnavbar.template%, [] ]
        tags:
            # The alias is what is used to retrieve the menu
            - { name: knp_menu.renderer, alias: subnavbar }

    mopa_bootstrap.subnavbar.twig.extension:
        class: Mopa\Bundle\BootstrapBundle\Navbar\Twig\SubnavbarExtension
        arguments: [ @mopa_bootstrap.subnavbar_renderer ]
        tags:
            -  { name: twig.extension }