<?php

namespace opwoco\Bundle\BootstrapBundle\Entity;

use Doctrine\ORM\EntityRepository;
use opwoco\Bundle\BootstrapBundle\Constant\IconSet;

/**
 * BootstrapIconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BootstrapIconRepository extends EntityRepository
{


    public function createOrUpdateIcon($identifier, $fontSet)
    {
        /** @var BootstrapIcon $entity */
        $entity = $this->findIconByIdentifier($identifier);
        $isNew = false;
        if (!$entity) {
            $entity = new BootstrapIcon();
            $isNew = true;
        }
        switch ($fontSet) {
            case IconSet::GLYPHICON: {
                $entity->setGlyphicon(true);
                break;
            }
            case IconSet::FONTAWESOME: {
                $entity->setFontawesome(true);
                break;
            }
            case IconSet::FOUNDATION: {
                $entity->setFoundation(true);
                break;
            }
            case IconSet::IONICONS: {
                $entity->setIonicons(true);
                break;
            }
            case IconSet::OCTICONS: {
                $entity->setOcticons(true);
                break;
            }
        }

        $em = $this->getEntityManager();
        if ($isNew) {
            $entity->setIdentifier($identifier);
            $em->persist($entity);
        }
        $em->flush();
    }

    private function findIconByIdentifier($identifer)
    {
        return $this->getEntityManager()->getRepository('opwocoBootstrapBundle:BootstrapIcon')
            ->findOneBy(array('identifier' => $identifer));
    }
}
