services:
    mopa_bootstrap.examplemenu_builder:
        class: %mopa_bootstrap.navbar.generic%
        arguments: ["MopaBootstrapBundle", true, "mopa_bootstrap_welcome", @mopa_bootstrap.examplemenu, @mopa_bootstrap.exampledropdown]
        # Make the navbar fluid for use in container-fluid.
        #calls:
        #    - [ setFluid, [ true ] ]
        tags:
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar } # The alias is what is used to retrieve the navbar
